sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
env:
  - DOCKER_GOOGLE_CREDENTIALS=$TRAVIS_BUILD_DIR/travis-sa.json
git:
  depth: 1
script:
  - mvn deploy
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/google-cloud-sdk/"
before_install:
  - openssl aes-256-cbc -K $encrypted_60b5de841810_key -iv $encrypted_60b5de841810_iv -in .travis-sa.json.enc -out travis-sa.json -d
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account travis@powop-1349.iam.gserviceaccount.com --key-file travis-sa.json
  - export TAG=`git rev-parse --short HEAD`
