language: java
jdk:
  - oraclejdk8
sudo: required
git:
  depth: 1
  submodules: false
services:
  - docker
install: true # This runs the "true" command in the install phase; thus skipping install. Installation done by mvn deploy
script:
  - mvn deploy
# deploys the latest tag of the app _only_. If you want to deploy solr or the indexer it
# must be done manually
  - ./deploy.sh
before_install:
# decrypt secrets
  - sh ./.decrypt.sh
  - tar xvf .travis-secrets.tar

cache:
  directories:
    - "$HOME/.m2"
