version: '2'

services:
  web:
    image: ipni/ipni-web:latest
    ports:
      - "18080:8080"
    volumes:
      - $SOURCE_DIRECTORY/ipni-web/web/target/web-0.0.1-SNAPSHOT.jar:/web.jar
    links:
      - solr
  indexer:
    image: ipni/ipni-indexer:latest
    ports:
      - "28080:8080"
    links:
      - solr
      
  solr:
    image: ipni/ipni-solr:latest
    ports:
      - "18983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ipni_1/data

volumes:
  solr_data: {}
