version: '2'

services:
  web:
    build: web/
    ports:
      - "18080:8080"
    volumes:
      - $SOURCE_DIRECTORY/ipni-web/web/target/web.jar:/web.jar
    links:
      - solr

  indexer:
    build: indexer/
    links:
      - solr
      
  solr:
    build: solr/
    ports:
      - "18983:8983"
    volumes:
      - solr_data_1:/opt/solr/server/solr/ipni_1/data
      - solr_data_2:/opt/solr/server/solr/ipni_2/data
      - solr_coreconf:/coreconf

volumes:
  solr_data_1: {}
  solr_data_2: {}
  solr_coreconf: {}
