apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexer
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.indexer.replicas }}
  template:
    metadata:
      labels:
        app: indexer
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: indexer
          image: "{{ .Values.indexer.repository }}:{{ .Values.indexer.tag }}"
          imagePullPolicy: {{ .Values.indexer.pullPolicy }}
          env:
            - name: BUILD_ONSTARTUP
              value: "true"
            - name: IPNI_FLAT
              value: https://storage.googleapis.com/kew-dev-backup/ipni_flat_all.csv.xz
