apiVersion: batch/v1
kind: Job
metadata:
  name: indexer-job
  labels:
    app: ipni
    chart: ipni-0.1.0
    release: beta
    heritage: Tiller
spec:
  template:
    metadata:
      labels:
        app: indexer-job
        release: beta
    spec:
      containers:
        - name: indexer-job
          image: "eu.gcr.io/ipni-1867/ipni/indexer:8318124"
          imagePullPolicy: Always
          env:
            - name: BUILD_ONSTARTUP
              value: "true"
      restartPolicy: Never
