replicaCount: 1
image:
  repository: eu.gcr.io/powop-1349/ipni/app
  tag: "ee16e17"
  pullPolicy: Always
service:
  name: ipni
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
indexer:
  repository: eu.gcr.io/powop-1349/ipni/indexer
  tag: "395ec09"
  pullPolicy: Always
  replicas: 0
solr:
  cores:
    - ipni_1
    - ipni_2
  image:
    repository: eu.gcr.io/powop-1349/ipni/solr
    tag: "8db0426"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious 
  # choice for the user. This also increases chances charts run on environments with little 
  # resources, such as Minikube. If you do want to specify resources, uncomment the following 
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
